# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_invoice_constraint_chronology
#
# Translators:
# OCA Transbot <transbot@odoo-community.org>, 2017
# Stefano <stefano.sforzi@agilebg.com>, 2018
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 10.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-03-01 01:41+0000\n"
"PO-Revision-Date: 2018-03-01 01:41+0000\n"
"Last-Translator: Stefano <stefano.sforzi@agilebg.com>, 2018\n"
"Language-Team: Italian (https://www.transifex.com/oca/teams/23907/it/)\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: account_invoice_constraint_chronology
#: model:ir.model.fields,field_description:account_invoice_constraint_chronology.field_account_journal_check_chronology
msgid "Check chronology"
msgstr "Controllo cronologia"

#. module: account_invoice_constraint_chronology
#: code:addons/account_invoice_constraint_chronology/model/account_invoice.py:31
#, python-format
msgid ""
"Chronology Error. Please confirm older draft invoices before %s and try "
"again."
msgstr ""
"Errore cronologico. Confermare le fatture in stato bozza prima del  %s e "
"riprovare."

#. module: account_invoice_constraint_chronology
#: code:addons/account_invoice_constraint_chronology/model/account_invoice.py:48
#, python-format
msgid ""
"Chronology Error. There exist at least one invoice with a date posterior to "
"%s."
msgstr ""
"Errore cronologico. Esiste almeno una fattura con data successiva a %s."

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_invoice
msgid "Invoice"
msgstr "Fattura"

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_journal
msgid "Journal"
msgstr "Sezionale"
